# Generated by Django 5.1.6 on 2026-02-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
